name: vttr
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  carousel_slider: ^4.2.1
  http: ^0.13.6
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.11
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  fluttertoast: ^8.2.2
  confetti: ^0.7.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  dio: ^5.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/

  fonts:
    - family: Rubki
      fonts:
        - asset: assets\fonts\Rubik-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets\fonts\Roboto-thin.ttf
        - asset: assets\fonts\Roboto-Regular.ttf
        - asset: assets\fonts\Roboto-Medium.ttf
        - asset: assets\fonts\Roboto-Bold.ttf


      