// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMadXI7qDj3uE7u2cqcXYbgEQCCmlRGwU',
    appId: '1:836208584309:web:727744c9385134bbbe7a3c',
    messagingSenderId: '836208584309',
    projectId: 'vttr-app',
    authDomain: 'vttr-app.firebaseapp.com',
    storageBucket: 'vttr-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdR0KTxd2uIbTMBCeDrY7gLKM8cuby50',
    appId: '1:836208584309:android:dd923dc6aefe4f02be7a3c',
    messagingSenderId: '836208584309',
    projectId: 'vttr-app',
    storageBucket: 'vttr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8E4K_dMCCBN-gkIHjpiFPTvEznmYri1E',
    appId: '1:836208584309:ios:27192c80c16bd506be7a3c',
    messagingSenderId: '836208584309',
    projectId: 'vttr-app',
    storageBucket: 'vttr-app.appspot.com',
    iosClientId: '836208584309-g4ftstpu07oo7ac6hbabfuvj36ta1sco.apps.googleusercontent.com',
    iosBundleId: 'com.example.vttr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8E4K_dMCCBN-gkIHjpiFPTvEznmYri1E',
    appId: '1:836208584309:ios:27192c80c16bd506be7a3c',
    messagingSenderId: '836208584309',
    projectId: 'vttr-app',
    storageBucket: 'vttr-app.appspot.com',
    iosClientId: '836208584309-g4ftstpu07oo7ac6hbabfuvj36ta1sco.apps.googleusercontent.com',
    iosBundleId: 'com.example.vttr',
  );
}
